Desktop Theme Integration with Webapp
mattermost/desktop pull request #1428
Opened 2020-12-14 19:23 UTC by devinbinnie

**Summary**
This PR adds integration of webapp themes into the desktop. It will replace the existing light/dark theme with whatever theme the webapp is using.

Based on the existing BrowserView code since we're moving to that.

What's done:
- Desktop app changes theme when the webapp theme changes via Account Settings or between teams
- Desktop app changes theme when different servers are selected
- Theme is pulled down directly from the server on initial load

What's not done:
- Websocket stuff to update the theme on prefs change (I really wanted to do this :()
- A bug that pops up parsing the JSON sometimes
- Exact choice of colour mapping from webapp theme > desktop theme (just took a general stab at it)
- Various other edge cases

2020-12-14 21:10 UTC, esethna commented
This is cool! @devinbinnie which theme color variable from webapp is used for the server tab bar?

2020-12-14 21:17 UTC, devinbinnie commented
> This is cool! @devinbinnie which theme color variable from webapp is used for the server tab bar?

It's using stuff from the sidebar, so I think that one is the sidebar header background.

2020-12-23 10:19 UTC, Willyfrog requested changes
love this change, the first one to talk with the server 🙌 

added a few comments for handling errors, messages and code structure, but looking mostly good.

One question: if a user is connected to multiple tabs, what would be the theme applied? does it change when the user switches tabs?

2020-12-23 10:19 UTC, Willyfrog commented on src/main/MattermostView.js
> +      const prefs = JSON.parse(prefsRaw);
```suggestion
let prefs;
try {
      prefs = JSON.parse(prefsRaw);
} catch e {
      log.error(`Error loading user theme for ${this.server.name}: ${e}`);
      WindowManager.sendToRenderer('use-default-theme');
      return;
}
```

2020-12-23 10:19 UTC, Willyfrog commented on src/main/MattermostView.js
> +        const themePref = themePrefs.find((pref) => pref.name === '');
```suggestion
      const themePref = themePrefs.find((pref) => pref.category === 'theme' && pref.name === '');
      if (themePref) {
```

2020-12-23 10:19 UTC, Willyfrog commented on src/main/MattermostView.js
> +        WindowManager.sendToRenderer('use-custom-theme', themeData);
```suggestion
        try {
            const themeData = JSON.parse(themePref.value);
            WindowManager.sendToRenderer('use-custom-theme', themeData);
        } catch e {
            console.log(`error parsing theme data for ${this.server.name}: ${e}`);
            WindowManager.sendToRenderer('use-default-theme');
        }
```

2021-01-12 00:18 UTC, esethna commented
@matthewbirtch thoughts on this from a UX perspective?

2021-01-12 21:17 UTC, matthewbirtch commented
@devinbinnie how can I test this on my local? I'm having a hard time seeing the sidebar theme colors working for the server tab bar, but need to see it for myself.

Also, the server tab bar is more of an OS window bar, so shouldn't it match the OS dark/light settings?

2021-01-12 21:23 UTC, devinbinnie commented
/update-branch

2021-01-12 21:23 UTC, mattermod commented
Error trying to update the PR.
Please do it manually.

2021-03-16 18:51 UTC, devinbinnie commented
Closing this until we decide whether we want to do it or not.

2021-03-16 18:51 UTC, closed without merging