[MM-31570] update mentions/unreads/session on jewel, tray and dock
mattermost/desktop pull request #1460
Opened 2021-01-29 16:08 UTC by Willyfrog

Please provide the following information:

**Summary**

update's app with number of mentions and if there is any unread or expired session.

**Issue link**
[MM-31570](https://mattermost.atlassian.net/browse/MM-31570)
**Test Cases**
using different servers (versions below v5.28 and above) and new sidebar configurations
- receive and read mentions
- mark channel as unread (either by messaging or using mark as unread)
- disconnect other user

badge, tab and dock should update accordingly

**Additional Notes**
while the initial change to support figure out how to get the mentions was easy, moving this information around wasn't so. Detecting if the server has unread channels varies depending on the server version and sidebar. For version up to v5.28, it will be noted by using an asterisk in the titlebar, after that we'll wait for favicon to change to notice if it was set as unread. Since name is obscured by webpack, we have to figure out what does it mean to have one favicon or the other and memoize it. So the first time a new favicon appears, we'll have to do a quick scan of the page and see if one of the teams is unread and if there is only one team search for an unread channel. 

Added a new appState to handle information and distribute, I was planning to do something similar once we started listening to the WS but seemed the right solution for this case. Any other state we need to have can be tied to this as well in the future

Also moved all the tray related info to a single file, removing it from being in multiple places. this process already started with browserview but now is more consistent. We should do the same with the badge, but there is still a few things in other files, but was totally out of this already-too-big PR.

One thing is left to improve, currently detecting if session is disconnected we are using an interval to figure it out. having some event we could listen would be a much better experience

2021-01-29 16:16 UTC, Willyfrog commented
I still have to test on windows/linux but shouldn't change too significantly

2021-01-29 18:20 UTC, devinbinnie commented on src/main/preload/mattermost.js
> +    ipcRenderer.send(NOTIFY_MENTION, title, body, channel, teamId, silent, messageData);
Shouldn't this be `data`?

2021-01-29 18:23 UTC, devinbinnie approved these changes

2021-02-01 23:10 UTC, deanwhillier requested changes
A few minor things for consideration.

2021-02-01 23:10 UTC, deanwhillier commented on src/main/MattermostView.js
> +}
Add newline
```suggestion
}

```

2021-02-01 23:10 UTC, deanwhillier commented on src/common/communication.js
> +export const UPDATE_BADGE = 'update_badge';
Add newline
```suggestion
export const UPDATE_BADGE = 'update_badge';

```

2021-02-04 11:44 UTC, Willyfrog commented on src/main/main.js
> +  getTrayImages(config.trayIconTheme);
I'll rename to refresh, but the function still returns the tray images in case they are needed

2021-02-04 11:48 UTC, Willyfrog reviewed
addressed comments
I'll be able to push once I get my admin rights back (i did a rebase with `browser-view` branch and now I can't force-push)

2021-02-05 16:39 UTC, deanwhillier approved these changes

2021-02-05 16:40 UTC, merged