@devinbinnie [MM-33434] Upgrade to Electron v11, some other dependency upgrades
mattermost/desktop pull request #1501
Opened 2021-03-04 15:07 UTC by devinbinnie

**Summary**
Upgraded to Electron v11

**Issue link**
https://mattermost.atlassian.net/browse/MM-33434

2021-03-04 16:26 UTC, Willyfrog requested changes
spectron should be upgraded with each major version of electron, in this case: ^13.0.0 See [Version Mapping](https://github.com/electron-userland/spectron#version-map)

also, not to fix it here, but they added [resized and moved events to browserview](https://github.com/electron/electron/pull/26454) which might reduce some code/glitches when resizing that we had in the past.

Looking good and looking forward to testing a native build on M1 🎉

2021-03-04 21:03 UTC, Willyfrog approved these changes

2021-03-05 11:33 UTC, wget commented
@Willyfrog And if you need M1 devices to test, these are as expensive as 2.4 EUR / day at Scaleway :)

![Screenshot_20210305_123307](https://user-images.githubusercontent.com/2997662/110110333-f863be80-7dae-11eb-9e1e-1056649b70e6.png)

2021-03-05 13:27 UTC, Willyfrog commented
> @Willyfrog And if you need M1 devices to test, these are as expensive as 2.4 EUR / day at Scaleway :)
> 
> ![Screenshot_20210305_123307](https://user-images.githubusercontent.com/2997662/110110333-f863be80-7dae-11eb-9e1e-1056649b70e6.png)

Thanks for the recommendation, I already have one for testing. But that seems like a really nice alternative and I'll keep it in mind

2021-03-05 15:10 UTC, hmhealey approved these changes

2021-03-05 15:11 UTC, merged