add PR/Issue template and release notes section in the PR template
mattermost/desktop pull request #1536
Opened 2021-04-14 11:07 UTC by cpanato

#### Summary
Add a release not section in the PR template to facilitate the release note process.

After this PR get approval, I will setup the webhook

#### Ticket Link
JIRA: https://mattermost.atlassian.net/browse/DOPS-371

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
- [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
- [ ] executed `npm run lint:js` for proper code formatting

#### Device Information
This PR was tested on: N/A
#### Screenshots
N/A

#### Release Note

```release-note
NONE
```

2021-04-14 13:04 UTC, amyblais approved these changes

2021-04-14 13:06 UTC, amyblais commented on .github/PULL_REQUEST_TEMPLATE.md
> +  Fixes https://github.com/mattermost/mattermost-server/issues/XXXXX
```suggestion
  Fixes https://github.com/mattermost/desktop/issues/XXXXX
```

2021-04-14 13:06 UTC, amyblais commented on .github/PULL_REQUEST_TEMPLATE.md
> +If the PR includes UI changes, include screenshots/GIFs (for both iOS and Android if possible).
```suggestion
If the PR includes UI changes, include screenshots/GIFs.
```

2021-04-14 13:06 UTC, amyblais commented on .github/PULL_REQUEST_TEMPLATE.md
> +* Websocket additions or changes
These can likely be removed.

2021-04-15 08:58 UTC, Willyfrog requested changes
looking good minus some comments that doesn't apply to desktop.

also a question: how does this affect anything we have setup in the templates section of the repository? (see https://github.com/mattermost/desktop/issues/templates/edit )

2021-04-15 08:58 UTC, Willyfrog commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Includes text changes and localization file updates
we currently don't have any localization, so this can be removed for the time being

2021-04-19 12:31 UTC, Willyfrog approved these changes

2021-04-19 22:43 UTC, mkraft approved these changes

2021-04-21 09:08 UTC, cpanato commented
@amyblais @mkraft the bot to apply labels for the release notes is up and running for this Repo.

After we merge this, need to review the open PRs to add or not the release notes

2021-04-21 09:08 UTC, merged