[MM-34890][MM-34897] Fix some fullscreen issues
mattermost/desktop pull request #1546
Opened 2021-04-16 19:21 UTC by devinbinnie

**Summary**
Fix 2 full-screen issues:
- Fullscreen status wouldn't restore when the app was restarted
- When opening the settings window in fullscreen mode, the window would get stuck in fullscreen and there was no way of getting out of it, so I've prevented the window from full-screening at all on opening.

**Issue link**
https://mattermost.atlassian.net/browse/MM-34890
https://mattermost.atlassian.net/browse/MM-34897

2021-04-16 20:24 UTC, Willyfrog requested changes
mostly looks good, I think we can improve the bounds-info.json content so we don't have to guess.

2021-04-16 20:24 UTC, Willyfrog commented on src/main/windows/mainWindow.js
> +    const fullscreen = process.platform === 'darwin' && windowIsMaximized && windowOptions.x === 0 && windowOptions.y === 0;
since we save the info in the file, why not save the fullscreen state so we don't have to guess if it is fullscreen or maximized?

2021-04-17 13:53 UTC, lieut-data approved these changes

2021-04-19 08:58 UTC, Willyfrog approved these changes

2021-04-19 08:59 UTC, merged

2021-04-19 09:52 UTC, Willyfrog commented
@devinbinnie can you cherry-pick this into 4.7?

2021-04-19 14:08 UTC, devinbinnie commented
/cherry-pick release-4.7

2021-04-19 14:08 UTC, mattermod commented
Cherry pick is scheduled.

2021-04-19 14:08 UTC, mattermod commented
Error trying doing the automated Cherry picking. Please do this manually

```
fatal: No such remote 'upstream'

+++ Returning you to the master branch and cleaning up.

```