[MM-40573] Stop asking detection on versions newer than 5.28, force space for the others
mattermost/desktop pull request #1931
Opened 2021-12-16 20:30 UTC by devinbinnie

#### Summary
If you are on a channel that begins with an asterisk, even if the server had no unreads it would show unreads.

This was caused by the regex we used to parse out the title for unreads/mentions. 

This PR stops that process from being used by versions newer than 5.28, and at least ensures you must have a space when searching for the asterisk on older versions.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-40573
Closes https://github.com/mattermost/desktop/issues/1690

```release-note
Fixed an issue where being on a channel with an asterisk at the front would cause unreads to return a false positive.
```

2021-12-17 05:12 UTC, M-ZubairAhmed approved these changes

2021-12-17 12:16 UTC, Willyfrog requested changes

2021-12-17 14:34 UTC, devinbinnie commented on src/main/views/MattermostView.ts
> +    titleParser = /(\((\d+)\) )?(\*\s)?/g
Makes sense, I changed it to an explicit space.

2021-12-22 10:59 UTC, Willyfrog approved these changes

2021-12-23 21:49 UTC, merged