[MM-39661] MM-T827 Select Next/Previous Tab
mattermost/desktop pull request #1964
Opened 2022-01-23 12:50 UTC by shadowshot-x

#### Summary

Added End to End tests for Tab change monitoring.

#### Ticket Link

#### Checklist

- [x] Added E2E tests
- [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
- [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
- [x] executed `npm run lint:js` for proper code formatting

#### Device Information
This PR was tested on:  Mac OS - Big Sur, v11.4

#### Release Note

```release-note
NONE
```

2022-01-23 12:50 UTC, mattermod commented
Hello @shadowshot-x,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-01-24 14:50 UTC, devinbinnie requested changes
@shadowshot-x Thanks for the PR!

Unfortunately this approach is not what is required for this test. You will need to use RobotJS to navigate the application menu (hence why you need to navigate to Window first) and select the tabs from there. There are examples of RobotJS you can use in the codebase.

2022-01-26 17:03 UTC, devinbinnie requested changes
Thanks for the PR @shadowshot-x!
I have a comment for you to review.

2022-02-04 16:24 UTC, shadowshot-x commented on e2e/specs/menu_bar/window_menu.test.js
> +        robot.keyTap('2', [process.platform === 'darwin' ? 'command' : 'control']);
Absolutely Correct. I will make the changes and push this weekend. Sorry for the late reply, was a bit busy this week

2022-02-15 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @aspleenic

2022-03-21 19:51 UTC, devinbinnie commented
@shadowshot-x Are you still around to finish this up?

2022-04-06 14:26 UTC, devinbinnie approved these changes

2022-04-07 12:38 UTC, M-ZubairAhmed approved these changes

2022-04-07 19:25 UTC, merged