[MM-44931] Allow zoom in/out when Shift is pressed
mattermost/desktop pull request #2178
Opened 2022-06-29 11:47 UTC by tboulis

#### Summary
Add hidden MenuItems that add keyboard shortcuts for Zoom In/Out when Shift is pressed.
I tried using the default role for `zoomIn` and `zoomOut` that electron provides, but it didn't work on Windows, so I followed this approach.

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-44931

#### Checklist

- [x] Added or updated e2e tests
- [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
- [x] completed [Mattermost Contributor Agreement](https://mattermost.com/contribute/)
- [x] executed `npm run lint:js` for proper code formatting

#### Device Information
This PR was tested on:
- macbook pro, Macos Monterey 12.4 
- pc, Windows 11
- pc, Ubuntu 22

#### Release Note
```release-note
Fix zoom in/out not working when Shift is pressed.
```

2022-06-29 11:47 UTC, mattermod commented
Hello @tboulis,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-06-29 13:09 UTC, mattermod commented
Building app in separate branch.

2022-06-29 13:28 UTC, devinbinnie requested changes
Thanks for the PR @tboulis!
Everything looks great and works well, I just had a couple requests for better code organization.

2022-06-29 13:28 UTC, devinbinnie commented on e2e/specs/menu_bar/view_menu.test.js
> +    it('MM-44931 Zoom in when CmdOrCtrl+Shift+Plus is pressed', async () => {
Thanks for adding these tests!
For better organization, I'd like to add this as part of the MM-T818 test case, which is in the same file. So what we can do here is put them both under a `describe()` with the label `MM-T818` and add this one as part 2. Have a look at the other test files and you can see how we split up the pieces.

2022-06-29 13:32 UTC, mattermod commented
Artifact links:  
https://output.circle-artifacts.com/output/job/b468e79a-7efe-4220-a2ca-adfde5e81ca5/artifacts/0/tmp/artifacts/mattermost-desktop-5.2.0-develop.1-linux-ia32.tar.gz  
https://output.circle-artifacts.com/output/job/b468e79a-7efe-4220-a2ca-adfde5e81ca5/artifacts/0/tmp/artifacts/mattermost-desktop-5.2.0-develop.1-linux-x64.tar.gz  
https://output.circle-artifacts.com/output/job/88e0382e-3ea4-42f1-8830-826fde60f0ff/artifacts/0/tmp/artifacts/mattermost-desktop-5.2.0-develop.1-mac-m1.dmg  
https://output.circle-artifacts.com/output/job/88e0382e-3ea4-42f1-8830-826fde60f0ff/artifacts/0/tmp/artifacts/mattermost-desktop-5.2.0-develop.1-mac-x64.dmg  
https://output.circle-artifacts.com/output/job/3ffbb3d3-a76f-418d-9c7e-5ea1d0bf76ec/artifacts/0/tmp/artifacts/mattermost-desktop-setup-5.2.0-develop.1-win.exe

2022-06-30 13:24 UTC, devinbinnie requested changes
One last little thing

2022-06-30 13:24 UTC, devinbinnie commented on e2e/specs/menu_bar/view_menu.test.js
> +        it('MM-44931 Zoom in when CmdOrCtrl+Shift+Plus is pressed', async () => {
All looks good, I just wanted to name the test cases for the test cases we have stores in JIRA.

```suggestion
        it('MM-T818_1 Zoom in when CmdOrCtrl+Shift+Plus is pressed', async () => {
```

2022-06-30 13:24 UTC, devinbinnie commented on e2e/specs/menu_bar/view_menu.test.js
> +        it('MM-44931 Zoom out when CmdOrCtrl+Shift+Minus is pressed', async () => {
```suggestion
        it('MM-T819_1 Zoom out when CmdOrCtrl+Shift+Minus is pressed', async () => {
```

2022-06-30 13:38 UTC, devinbinnie approved these changes
Thanks @tboulis! Looks good now!

2022-06-30 18:14 UTC, hmhealey approved these changes
Thanks for the PR! I wouldn't have thought you could just hide a menu item (vs removing it entirely), but that works for me

2022-06-30 18:14 UTC, merged