Make writeToFile return a Promise in JsonFileManager
mattermost/desktop pull request #2246
Opened 2022-08-29 16:02 UTC by tboulis

#### Summary
Make `JsonFileManager.writeToFile()` return a Promise instead of void. 

#### Release Note
```release-note
NONE
```

2022-08-29 16:05 UTC, devinbinnie approved these changes

2022-08-29 21:12 UTC, hmhealey requested changes

2022-08-29 21:12 UTC, hmhealey commented on src/common/JsonFileManager.ts
> +                    reject(err);
Did you mean to return after rejecting the Promise?

2022-09-01 16:42 UTC, hmhealey approved these changes

2022-09-01 16:42 UTC, merged