[MM-36456] Add support for Gnome's do-not-disturb
mattermost/desktop pull request #2278
Opened 2022-10-12 11:56 UTC by tboulis

#### Summary
Currently on Linux the notifications do not respect "Do not disturb" value in settings. I added a function that uses the command `gsettings get org.gnome.desktop.notifications show-banners` to check if do-not-disturb is ON.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-36456

#### Device Information
This PR was tested on: `Ubuntu Desktop 22.04.1 LTS`

#### Release Note
```release-note
Added support for Gnome's "do-not-disturb"
```

2022-10-12 12:30 UTC, m1lt0n approved these changes
Good one!

2022-10-14 13:39 UTC, mattermod commented
Building app in separate branch.

2022-10-14 13:40 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/desktop/23589  
https://circleci.com/gh/mattermost/desktop/23588  
https://circleci.com/gh/mattermost/desktop/23587

2022-10-14 14:11 UTC, mattermod commented
Artifact links:  
https://output.circle-artifacts.com/output/job/5367ba81-2f63-491d-a49b-8a2acfa98b1b/artifacts/0/tmp/artifacts/mattermost-desktop-5.2.0-develop.1-win-ia32.zip  
https://output.circle-artifacts.com/output/job/5367ba81-2f63-491d-a49b-8a2acfa98b1b/artifacts/0/tmp/artifacts/mattermost-desktop-5.2.0-develop.1-win-x64.zip  
https://output.circle-artifacts.com/output/job/20ebba7c-9581-4c63-aaee-5591e4d33bd7/artifacts/0/tmp/artifacts/mattermost-desktop-5.2.0-develop.1-mac-m1.dmg  
https://output.circle-artifacts.com/output/job/20ebba7c-9581-4c63-aaee-5591e4d33bd7/artifacts/0/tmp/artifacts/mattermost-desktop-5.2.0-develop.1-mac-x64.dmg  
https://output.circle-artifacts.com/output/job/169ddf86-e1fb-4366-bd2d-c2d42e82a7e8/artifacts/0/tmp/artifacts/mattermost-desktop-5.2.0-develop.1-linux-x64.tar.gz

2022-10-14 15:54 UTC, devinbinnie requested changes
DND setting seems to be backwards, I'm seeing notifications when DND is on in GNOME.

2022-10-17 12:44 UTC, mattermod commented
Building app in separate branch.

2022-10-17 12:44 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/desktop/23644  
https://circleci.com/gh/mattermost/desktop/23643  
https://circleci.com/gh/mattermost/desktop/23642

2022-10-17 13:18 UTC, mattermod commented
Artifact links:  
https://output.circle-artifacts.com/output/job/d5a2e307-194a-407f-a8a1-64138753ffe5/artifacts/0/tmp/artifacts/mattermost-desktop-5.2.0-develop.1-linux-x64.tar.gz  
https://output.circle-artifacts.com/output/job/ba528e6e-d8d0-498e-baad-037061160fc9/artifacts/0/tmp/artifacts/mattermost-desktop-5.2.0-develop.1-win-ia32.zip  
https://output.circle-artifacts.com/output/job/ba528e6e-d8d0-498e-baad-037061160fc9/artifacts/0/tmp/artifacts/mattermost-desktop-5.2.0-develop.1-win-x64.zip  
https://output.circle-artifacts.com/output/job/5d49ada8-699b-4b5d-a7d0-861ca10deafb/artifacts/0/tmp/artifacts/mattermost-desktop-5.2.0-develop.1-mac-m1.dmg  
https://output.circle-artifacts.com/output/job/5d49ada8-699b-4b5d-a7d0-861ca10deafb/artifacts/0/tmp/artifacts/mattermost-desktop-5.2.0-develop.1-mac-x64.dmg

2022-10-17 13:32 UTC, devinbinnie commented on src/main/notifications/dnd-linux.ts
> +        log.error('getLinuxDoNotDisturb', {error});
Yeah the only reason I say is that the message is the same, and the console log doesn't differentiate (even though the file does)

2022-10-17 13:37 UTC, devinbinnie approved these changes
Working well now :)

2022-10-17 13:37 UTC, merged