Replace deprecated "gpu-process-crashed" with "child-process-gone"
mattermost/desktop pull request #2471
Opened 2022-12-13 13:58 UTC by tboulis

#### Summary
I also passed the details as an argument and not concat them in the string in order to be displayed in the logs

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-49039

#### Screenshots
![5497A918-364C-4750-8CC4-119D4567749F](https://user-images.githubusercontent.com/24255041/207349339-30ab9796-452d-4937-a833-b58ec682484b.png)

#### Release Note
```release-note
NONE
```

2022-12-13 14:02 UTC, devinbinnie requested changes
Looks good! Just one request :P

2022-12-13 14:02 UTC, devinbinnie commented on src/main/app/initialize.ts
> +    app.on('child-process-gone', handleChildProcessGone);
Can we handle both events using this handler? Not sure if they differ at all but just to make sure we cover all bases.

2022-12-13 14:12 UTC, devinbinnie approved these changes

2022-12-14 08:47 UTC, m1lt0n approved these changes

2022-12-14 08:49 UTC, merged