Cherry-pick GitHub Actions to 5.3
mattermost/desktop pull request #2600
Opened 2023-03-09 15:27 UTC by devinbinnie

#### Summary
In anticipation of a new release, I think it's best we try the new release process on the build to make sure it works.

```release-note
NONE
```

2023-03-09 15:32 UTC, amyblais commented
> cc @amyblais making sure this is okay with you. It shouldn't affect the final build of the app, just the release process.

Sounds good!

2023-03-09 15:33 UTC, toninis requested changes

2023-03-09 15:35 UTC, toninis commented on .github/workflows/release.yaml
> +        run: ./scripts/Makefile.ps1 install-deps
I mean it worked the other time without those but it failed in the other pipeline . So better add everything in place in order to be sure . 
We will have to revisit and make the pipelines more flexible and reusable

2023-03-09 15:40 UTC, mattermost-build commented
The files `.circleci/config.yml, scripts/patch_mas_version.sh, scripts/patch_mas_version.sh` are in the blocklist for external contributors. Hence, these changes are not tested by the CI pipeline active until the build is re-triggered by a core committer or the PR is merged. Please be careful when reviewing it.
/cc @mattermost/core-security @mattermost/core-build-engineers

2023-03-09 16:12 UTC, devinbinnie commented on .github/workflows/release.yaml
> +        run: ./scripts/Makefile.ps1 install-deps
Ahh right, I'll make a PR against master to add this and then cherry-pick over to this branch

2023-03-09 21:43 UTC, devinbinnie commented on .github/workflows/release.yaml
> +        run: ./scripts/Makefile.ps1 install-deps
https://github.com/mattermost/desktop/pull/2601

2023-03-10 13:10 UTC, mattermost-build commented
The files `.circleci/config.yml, scripts/patch_mas_version.sh, scripts/patch_mas_version.sh` are in the blocklist for external contributors. Hence, these changes are not tested by the CI pipeline active until the build is re-triggered by a core committer or the PR is merged. Please be careful when reviewing it.
/cc @mattermost/core-security @mattermost/core-build-engineers

2023-03-10 14:16 UTC, toninis approved these changes
🚀

2023-03-10 14:16 UTC, toninis commented
We will closely monitor during the release . @devinbinnie ping me in order to check together the progress when you trigger it

2023-03-10 14:17 UTC, merged